name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    # run on pushes or on PRs (but not on PR-close events)
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build, Export & Deploy

    steps:
      # 1) fetch your repo
      - uses: actions/checkout@v3

      # 2) pick a Node version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3) install deps
      - name: Install Dependencies
        run: npm ci

      # 4) build & export (next export → static files in out/)
      - name: Build & Export Static Site
        run: |
          npm run build
          npm run export

      # 5) deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # your SWA token, pasted into GitHub Secrets under this exact name:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FIELD_04A40C30F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}        # for PR comments, etc.
          action: "upload"
          app_location: "/"                              # we’re building from the repo root
          api_location: ""                               # no Functions/APIs
          output_location: "out"                         # next export → out/

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close SWA PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FIELD_04A40C30F }}
          action: "close"
